"""Add risk_tolerance to MutualFund model

Revision ID: a115adebaf63
Revises: 13dd70d9c7c3
Create Date: 2024-02-25 18:56:14.797421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a115adebaf63'
down_revision = '13dd70d9c7c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mutual_fund', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_tolerance', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mutual_fund', schema=None) as batch_op:
        batch_op.drop_column('risk_tolerance')

    # ### end Alembic commands ###
